name: talbati
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.3.4 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  bloc: ^8.1.4
  intl: ^0.19.0
  fluttertoast: ^8.2.6
  equatable: ^2.0.5
  permission_handler: ^11.3.1
  google_fonts: ^6.2.1
  flutter_screenutil: ^5.9.3
  get_storage: ^2.1.1
  flutter_bloc: ^8.1.5
  get: 4.6.6
  flutter: 
    sdk: flutter
  flutter_svg: ^2.0.10+1

dev_dependencies: 
  flutter_lints: ^3.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
    - assets/icons/
  uses-material-design: true

